<a href="https://colab.research.google.com/github/sujeengim/ALGORITHM/blob/main/silver5/2563.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 접근
100 *100 크기의 배열을 만들고
색종이가 놓이는 위치의 행열부분(셀들)을 count 한다.


count가 0인 것을 구하여 10000에서 빼준다.

# 1. 넘파이 사용

In [ ]:
import numpy as np

# 배열 초기화
squareList = np.array([[0] * 100 for _ in range(100)])



# 모든 행의 인덱스 1부터 3까지 값을 100으로 수정
arr[:, 1:4] = 100

print(arr)
출력:

lua
복사
편집
[[  1 100 100 100   5]
 [  6 100 100 100  10]
 [ 11 100 100 100  15]]

# 넘파이 사용 x

In [10]:
squareList = [[0] * 100 for _ in range(100)]
# len(squareList)

n = int(input())
cnt = 0

for _ in range(n):
    colstart, rowstart = map(int, input().split(' '))
    for indx in range(10):
        for indx2 in range(10):
            if (squareList[99-rowstart-indx2][colstart+indx] != 1):
                squareList[99-rowstart-indx2][colstart+indx] += 1 #마지막행의 인덱스는 99라서
                cnt+=1

# for row in squareList:
#     print(row)

print(cnt)

3
3 7
15 7
5 2
260


chat gpt에게 내 코드를 보여주고 더 효율적이고 실행이 빠른 코드를 알려달라고 했는데 실패했다.


내 코드와 메모리가 더 사용되거나 시간이 똑같이 걸리는 코드만 보여줄 뿐이다.

내 생각이지만 내 코드를 너무 참조해서 그 안에서 약간만 변형하여 보여주는 것 같다.
난 새로운 간결하고 효율적인 코드를 원하는데!

그래서 남들의 제출 코드를 보았다. 이걸 보면서 내 코드의 문제점을 찾아보겠다.

먼저 gpt가 알려준 코드 1
```python

# 100x100 크기의 평면을 1차원 배열로 관리
squareList = [0] * 10000  # 100 x 100 = 10000

n = int(input())  # 색종이 수
cnt = 0  # 색칠된 넓이

for _ in range(n):
    colstart, rowstart = map(int, input().split())
    for dx in range(10):
        for dy in range(10):
            # 1차원 인덱스 계산 (row * 100 + col)
            index = (rowstart + dy) * 100 + (colstart + dx)
            if squareList[index] == 0:
                squareList[index] = 1
                cnt += 1

print(cnt)

```

```python
n = int(input())  # 색종이 수
covered = set()  # 칠해진 좌표를 저장할 집합

for _ in range(n):
    colstart, rowstart = map(int, input().split())
    for dx in range(10):
        for dy in range(10):
            # 좌표를 튜플로 만들어 중복 여부를 관리
            point = (rowstart + dy, colstart + dx)
            covered.add(point)

# 최종적으로 칠해진 좌표의 개수를 출력
print(len(covered))

```

```python
# 100x100 크기의 도화지 배열 생성
squareList = [[0] * 100 for _ in range(100)]

n = int(input())  # 색종이 수
cnt = 0  # 색종이가 칠해진 영역의 넓이

for _ in range(n):
    colstart, rowstart = map(int, input().split())
    for dx in range(10):
        for dy in range(10):
            # 중복 없이 색칠되지 않은 부분만 채우기
            if squareList[rowstart + dy][colstart + dx] == 0:
                squareList[rowstart + dy][colstart + dx] = 1
                cnt += 1

print(cnt)


```

In [ ]:
# 내 코드보다 4ms 빠른 코드
n=int(input())
array = [[0 for i in range(100)] for j in range(100) ]
for _ in range(n):
    x, y = map(int, input().split())
    for i in range(x, x+10):
        for j in range(y, y+10):
            array[i][j] += 1
zero_sum=0
for i in range(100):
    zero_sum += array[i].count(0)
print(10000-zero_sum)

# 💡문제점 찾아내기
1. 이중 반복문 안에서 실행되는 문장에서 매번 똑같은 연산을 하고 있다.

$squareList[99-rowstart-indx2][colstart+indx]$ 이부분이다.

반복문 범위 설정에서 rowstart와 colstart를 사용하고
이중 반복문 안에서는 간단하게 처리해보자!


2. 이중 반복문 안에서 if 조건을 둘 필요가 없다.

count()를 사용해서 0의 개수를 세면 된다.

처음에는 count를 생각하지 못해서 if를 추가한거였다.

3. 문제에서 보여준 그림과 똑같이 구현하기 위해 $[99-rowstart-indx2]$ 이렇게 마지막행 99에서 rowstart를 빼준거였다. 하지만 그냥 그림이 뒤집어진거라고 생각하면 된다. 우리의 목적은 영역을 구하는 것이고, 그래프가 뒤집어지든 원본이든 차지하는 영역은 똑같으니까!

# 결론
실행시간이 최대 4ms 감소하는 코드 알아보았다.


In [11]:
# 1 반영한 코드 -> 시간 4ms 감소하였다.
squareList = [[0] * 100 for _ in range(100)]
# len(squareList)

n = int(input())
cnt = 0

for _ in range(n):
    colstart, rowstart = map(int, input().split(' '))
    for y in range(colstart, colstart-10, -1):
        for x in range(rowstart, rowstart+10, 1):
            if (squareList[x][y] != 1):
                squareList[x][y] += 1 #마지막행의 인덱스는 99라서
                cnt+=1

# for row in squareList:
#     print(row)

print(cnt)

3
3 7
15 7
5 2
260


In [14]:
# 2 반영한 코드 -> 시간 4ms 감소하였다.
squareList = [[0] * 100 for _ in range(100)]
# len(squareList)

n = int(input())

for _ in range(n):
    colstart, rowstart = map(int, input().split(' '))
    for indx in range(10):
        for indx2 in range(10):
            squareList[99-rowstart-indx2][colstart+indx] += 1 #마지막행의 인덱스는 99라서

# for row in squareList:
#     print(row)

zero_sum = 0
for i in range(100):
    zero_sum += squareList[i].count(0)

print(10000 - zero_sum)

3
3 7
15 7
5 2
260


In [16]:
# 1, 2, 3 모두 반영한 코드 -> 4ms 감소하였다.
squareList = [[0] * 100 for _ in range(100)]
# len(squareList)

n = int(input())

for _ in range(n):
    colstart, rowstart = map(int, input().split(' '))
    for y in range(colstart, colstart+10):
        for x in range(rowstart, rowstart+10):
            squareList[x][y] += 1 #마지막행의 인덱스는 99라서

# for row in squareList:
#     print(row)

zero_sum = 0
for i in range(100):
    zero_sum += squareList[i].count(0)

print(10000 - zero_sum)

3
3 7
15 7
5 2
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

# 배열 초기화 테스트

In [ ]:
lst = [0] * 5
lst

[0, 0, 0, 0, 0]

In [ ]:
lst2 = [[0] * 5 for _ in range(3)]
lst2

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [ ]:
lst2[:][1] = 1
lst2

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

제너레이터 특징
- 메모리 효율성: 모든 데이터를 한꺼번에 메모리에 올리지 않고 하나씩 생성.

- Lazy Evaluation: 필요할 때만 값을 생성하여 처리 속도가 빠름.

- 반복자(Iterator)와 유사: next() 함수를 통해 값을 하나씩 얻을 수 있음.

In [ ]:
lst3 = ([0] * 5 for _ in range(3))
lst3

<generator object <genexpr> at 0x7f96134f68e0>

In [ ]:
for i in lst3:
    print(i)

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [ ]:
import numpy

numpy.array([[0] * 5 for _ in range(3)])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
import numpy
lst4 = numpy.array([[0] * 5] * 3)
lst4


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
lst4[1:4, 1:3] = 1
lst4

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 1, 1, 0, 0]])

# 💡 문제의 원인: 얕은 복사
[[0] * 5] * 3은 동일한 리스트 객체를 3번 복사한 것입니다.
이로 인해 모든 행이 같은 객체를 가리키고 있어, 한 행의 값을 바꾸면 나머지 행도 함께 바뀝니다.

In [ ]:
lst5 = [[0] * 5] * 3
lst5

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [ ]:
lst5[1][2] = 1

In [ ]:
lst5

[[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0]]

## 위 문제 해결 방안

In [ ]:
# 각 행을 독립적으로 초기화
lst5 = [[0] * 5 for _ in range(3)]
lst5[1][2] = 1
print(lst5)

[[0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0]]


# 또 다른 테스트

In [ ]:
lst6 = [[0] * 5 for _ in range(3)]
lst6[1][2:] = 1
print(lst6)

TypeError: can only assign an iterable

In [ ]:
test = [[0]*10 for _ in range(10)]

r = 2
c = 3

for indx in range(3):
    for indx2 in range(3):
        test[r+indx][c+indx] = 1

test

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

SyntaxError: invalid syntax (<ipython-input-8-9c648f768fc9>, line 2)