<a href="https://colab.research.google.com/github/sujeengim/ALGORITHM/blob/main/silver5/2563.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 접근
100 *100 크기의 배열을 만들고
색종이가 놓이는 위치의 행열부분(셀들)을 count 한다.


count가 0인 것을 구하여 10000에서 빼준다.

# 1. 넘파이 사용

In [ ]:
import numpy as np

# 배열 초기화
squareList = np.array([[0] * 100 for _ in range(100)])



# 모든 행의 인덱스 1부터 3까지 값을 100으로 수정
arr[:, 1:4] = 100

print(arr)
출력:

lua
복사
편집
[[  1 100 100 100   5]
 [  6 100 100 100  10]
 [ 11 100 100 100  15]]

# 넘파이 사용 x

In [10]:
squareList = [[0] * 100 for _ in range(100)]
# len(squareList)

n = int(input())
cnt = 0

for _ in range(n):
    colstart, rowstart = map(int, input().split(' '))
    for indx in range(10):
        for indx2 in range(10):
            if (squareList[99-rowstart-indx2][colstart+indx] != 1):
                squareList[99-rowstart-indx2][colstart+indx] += 1 #마지막행의 인덱스는 99라서
                cnt+=1

# for row in squareList:
#     print(row)

print(cnt)

3
3 7
15 7
5 2
260


In [ ]:
# 내 코드보다 4ms 빠른 코드
n=int(input())
array = [[0 for i in range(100)] for j in range(100) ]
for _ in range(n):
    x, y = map(int, input().split())
    for i in range(x, x+10):
        for j in range(y, y+10):
            array[i][j] += 1
zero_sum=0
for i in range(100):
    zero_sum += array[i].count(0)
print(10000-zero_sum)

# 배열 초기화 테스트

In [ ]:
lst = [0] * 5
lst

[0, 0, 0, 0, 0]

In [ ]:
lst2 = [[0] * 5 for _ in range(3)]
lst2

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [ ]:
lst2[:][1] = 1
lst2

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

제너레이터 특징
- 메모리 효율성: 모든 데이터를 한꺼번에 메모리에 올리지 않고 하나씩 생성.

- Lazy Evaluation: 필요할 때만 값을 생성하여 처리 속도가 빠름.

- 반복자(Iterator)와 유사: next() 함수를 통해 값을 하나씩 얻을 수 있음.

In [ ]:
lst3 = ([0] * 5 for _ in range(3))
lst3

<generator object <genexpr> at 0x7f96134f68e0>

In [ ]:
for i in lst3:
    print(i)

[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]
[0, 0, 0, 0, 0]


In [ ]:
import numpy

numpy.array([[0] * 5 for _ in range(3)])

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
import numpy
lst4 = numpy.array([[0] * 5] * 3)
lst4


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
lst4[1:4, 1:3] = 1
lst4

array([[0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0],
       [0, 1, 1, 0, 0]])

# 💡 문제의 원인: 얕은 복사
[[0] * 5] * 3은 동일한 리스트 객체를 3번 복사한 것입니다.
이로 인해 모든 행이 같은 객체를 가리키고 있어, 한 행의 값을 바꾸면 나머지 행도 함께 바뀝니다.

In [ ]:
lst5 = [[0] * 5] * 3
lst5

[[0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [ ]:
lst5[1][2] = 1

In [ ]:
lst5

[[0, 0, 1, 0, 0], [0, 0, 1, 0, 0], [0, 0, 1, 0, 0]]

## 위 문제 해결 방안

In [ ]:
# 각 행을 독립적으로 초기화
lst5 = [[0] * 5 for _ in range(3)]
lst5[1][2] = 1
print(lst5)

[[0, 0, 0, 0, 0], [0, 0, 1, 0, 0], [0, 0, 0, 0, 0]]


# 또 다른 테스트

In [ ]:
lst6 = [[0] * 5 for _ in range(3)]
lst6[1][2:] = 1
print(lst6)

TypeError: can only assign an iterable

In [ ]:
test = [[0]*10 for _ in range(10)]

r = 2
c = 3

for indx in range(3):
    for indx2 in range(3):
        test[r+indx][c+indx] = 1

test

[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]

SyntaxError: invalid syntax (<ipython-input-8-9c648f768fc9>, line 2)